version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres:9.5
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
              #    gameengine:
              #        container_name: game_engine
              #        image: janderton/game_engine:latest
              #        ports:
              #            - "8080:80"
volumes:
    pgdata:
